javascripts:
  app:
    - public/javascripts/maps.js
stylesheets:
  app:
    - public/stylesheets/application.css
  admin:
    - public/stylesheets/scaffold.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_overrides.css
    - public/stylesheets/application.css
    